# Generated by Django 4.2.9 on 2024-03-09 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                ("consultantId", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("1", "Capital Specialist"),
                            ("2", "Financial Specialist"),
                            ("3", "Licensing Specialist"),
                            ("4", "Cultural Specialist"),
                            ("5", "Technology Specialist"),
                            ("6", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("bip_id", models.IntegerField()),
            ],
            options={"db_table": "consultants",},
        ),
    ]
