# Generated by Django 4.2.9 on 2024-03-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("1", "Capital Specialist"),
                    ("2", "Financial Specialist"),
                    ("3", "Licensing Specialist"),
                    ("4", "Cultural Specialist"),
                    ("5", "Technology Specialist"),
                    ("6", "Other"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="consultant",
            constraint=models.CheckConstraint(
                check=models.Q(("specialty__in", ["1", "2", "3", "4", "5", "6"])),
                name="valid_specialty",
            ),
        ),
    ]
