# Generated by Django 4.2.9 on 2024-03-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_consultant_slug_alter_consultant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInitiativeProgram',
            fields=[
                ('bip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('deliverables', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bips',
            },
        ),
        migrations.RenameField(
            model_name='consultant',
            old_name='consultantId',
            new_name='consultant_id',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='bip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.businessinitiativeprogram'),
        ),
    ]
