# Generated by Django 4.2.9 on 2024-03-31 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_businessinitiativeprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='bip_id',
        ),
        migrations.DeleteModel(
            name='BusinessInitiativeProgram',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
    ]
