# Generated by Django 4.2.9 on 2024-03-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_remove_consultant_bip_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
