# Generated by Django 4.2.9 on 2024-03-31 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_review_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('contact_submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact_submissions',
            },
        ),
        migrations.AddConstraint(
            model_name='contactsubmission',
            constraint=models.CheckConstraint(check=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='phone_or_email_required'),
        ),
        migrations.AddConstraint(
            model_name='contactsubmission',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_contact'),
        ),
    ]
