version: '3.9.6'

services:
  db:
    image: postgres:16.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: communidata-db
    ports:
      - 5433:5432
  datavisualizer:
    image: datavisualizer
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/Data_Visualizer
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
