# Generated by Django 4.2.9 on 2024-04-16 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_established',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 16, 21, 47, 5, 243052, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 21, 47, 5, 242517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 21, 47, 5, 242739, tzinfo=datetime.timezone.utc)),
        ),
    ]
