# Generated by Django 4.2.9 on 2024-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_business_date_established_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
