# Generated by Django 4.2.9 on 2024-04-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_remove_sessions_valid_session_date_and_more'),
    ]

    operations = [

    ]
