# Generated by Django 4.2.9 on 2024-04-17 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_remove_sessions_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='duration',
            field=models.DurationField(default='00:00:10'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', datetime.timedelta(0))), name='valid_duration'),
        ),
    ]
