# Generated by Django 4.2.9 on 2024-07-10 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0018_remove_business_valid_date_established_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='valid_date_established',
        ),
        migrations.RemoveConstraint(
            model_name='contacts',
            name='valid_date_of_birth',
        ),
        migrations.RemoveConstraint(
            model_name='contacts',
            name='valid_registration_date',
        ),
        migrations.RemoveConstraint(
            model_name='sessions',
            name='valid_session_date',
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('date_established__lte', datetime.date(2024, 7, 10))), name='valid_date_established'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2024, 7, 10))), name='valid_date_of_birth'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('registration_date__lte', datetime.date(2024, 7, 10))), name='valid_registration_date'),
        ),
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2024, 7, 10))), name='valid_session_date'),
        ),
    ]
