# Generated by Django 4.2.9 on 2024-04-10 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='PIN must be in the format 00-00-000-000-0000.', regex='^\\d{2}-\\d{2}-\\d{3}-\\d{3}-\\d{4}$')])),
                ('address', models.CharField(max_length=100)),
                ('address_number', models.IntegerField()),
                ('address_street', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('chicago_owned_property', models.BooleanField()),
                ('property_class', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Property class must be in the format 0-00.', regex='^\\d{1}-\\d{2}$')])),
                ('property_description', models.TextField()),
                ('tax_bill_2020', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_bill_2021', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessment_2020', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assessment_2021', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.IntegerField()),
                ('area_sq_ft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size_sf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_tax_year', models.IntegerField()),
                ('taxpayer_name', models.CharField(max_length=100)),
                ('taxpayer_address', models.CharField(max_length=100)),
                ('taxpayer_city_state_zip', models.CharField(max_length=100)),
                ('time_last_checked', models.DateTimeField()),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.AddConstraint(
            model_name='buildings',
            constraint=models.UniqueConstraint(fields=('pin', 'address_number'), name='unique_building'),
        ),
    ]
