# Generated by Django 4.2.9 on 2024-04-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_business_contacts_business_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.business')),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.consultant')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.contacts')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.AddConstraint(
            model_name='clients',
            constraint=models.UniqueConstraint(fields=('business_id', 'contact_id'), name='unique_client'),
        ),
    ]
