# Generated by Django 4.2.9 on 2024-04-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_business_description_alter_business_date_established_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.contacts'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.business'),
        ),
    ]
