# Generated by Django 4.2.9 on 2024-04-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_clients_clients_unique_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.clients')),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.consultant')),
            ],
            options={
                'db_table': 'advising_sessions',
            },
        ),
    ]
