# Generated by Django 4.2.9 on 2024-04-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_business_notes_business_num_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='business_id',
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.contacts'),
        ),
    ]
