# Generated by Django 4.2.9 on 2024-04-16 21:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ein',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='EIN must be in the format 00-0000000.', regex='^\\d{2}-\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='business',
            name='licenses',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='naics_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('industry__in', ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'])), name='valid_industry'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('date_established__lte', datetime.date(2024, 4, 16))), name='valid_date_established'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('legal_structure__in', ['1', '2', '3', '4', '5', '6', '7', '8'])), name='valid_legal_structure'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Active', 'Inactive', 'Closed'])), name='valid_status'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2024, 4, 16))), name='valid_date_of_birth'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['M', 'F', 'O', 'N'])), name='valid_gender_choice'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('registration_date__lte', datetime.date(2024, 4, 16))), name='valid_registration_date'),
        ),
    ]
