# Generated by Django 4.2.9 on 2024-04-17 00:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_remove_contacts_business_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='valid_date_established',
        ),
        migrations.RemoveConstraint(
            model_name='contacts',
            name='valid_date_of_birth',
        ),
        migrations.RemoveConstraint(
            model_name='contacts',
            name='valid_registration_date',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='business',
            name='ein',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='EIN must be in the format 00-0000000.', regex='^\\d{2}-\\d{7}$')]),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(check=models.Q(('date_established__lte', datetime.date(2024, 4, 17))), name='valid_date_established'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2024, 4, 17))), name='valid_date_of_birth'),
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.CheckConstraint(check=models.Q(('registration_date__lte', datetime.date(2024, 4, 17))), name='valid_registration_date'),
        ),
    ]
