# Generated by Django 4.2.9 on 2024-04-16 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_business_ein_alter_business_licenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 4, 16)),
        ),
        migrations.AddField(
            model_name='contacts',
            name='registration_date',
            field=models.DateField(default=datetime.date(2024, 4, 16)),
        ),
    ]
