# Generated by Django 4.2.9 on 2024-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_remove_business_valid_date_established_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_notes',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='clients',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Active', 'Inactive', 'Closed'])), name='valid_client_status'),
        ),
    ]
