# Generated by Django 4.2.9 on 2024-04-17 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_clients_client_notes_clients_valid_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='duration',
            field=models.DurationField(default='00:00:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='follow_up',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='notes',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2024, 4, 17))), name='valid_session_date'),
        ),
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Active', 'Inactive', 'Closed'])), name='valid_session_status'),
        ),
    ]
