# Generated by Django 4.2.9 on 2024-04-17 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_sessions_date_sessions_duration_sessions_follow_up_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessions',
            name='valid_session_date',
        ),
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2024, 4, 17))), name='valid_session_date'),
        ),
    ]
