# Generated by Django 4.2.9 on 2024-04-17 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_remove_sessions_valid_duration_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessions',
            constraint=models.CheckConstraint(check=models.Q(('duration__gt', datetime.timedelta(0))), name='valid_duration'),
        ),
    ]
