# Generated by Django 4.2.9 on 2024-04-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_remove_sessions_valid_duration_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessions',
            name='valid_duration',
        ),
    ]
