# Generated by Django 4.2.9 on 2024-04-16 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('contact_submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact_submissions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddConstraint(
            model_name='contactsubmission',
            constraint=models.CheckConstraint(check=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='phone_or_email_required'),
        ),
        migrations.AddConstraint(
            model_name='contactsubmission',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_contact'),
        ),
    ]
