# Generated by Django 4.2.9 on 2024-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLicenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_id', models.CharField()),
                ('license_id', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('site_number', models.IntegerField()),
                ('legal_name', models.CharField()),
                ('doing_business_as_name', models.CharField()),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zip_code', models.CharField()),
                ('ward', models.IntegerField()),
                ('precinct', models.IntegerField()),
                ('ward_precinct', models.CharField()),
                ('police_district', models.IntegerField()),
                ('license_code', models.IntegerField()),
                ('license_description', models.CharField()),
                ('business_activity_id', models.CharField()),
                ('business_activity', models.CharField()),
                ('license_number', models.IntegerField()),
                ('application_type', models.CharField()),
                ('application_created_date', models.DateTimeField()),
                ('application_requirements_complete', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('conditional_approval', models.CharField()),
                ('license_term_start_date', models.DateTimeField()),
                ('license_term_expiration_date', models.DateTimeField()),
                ('license_approved_for_issuance', models.DateTimeField()),
                ('date_issued', models.DateTimeField()),
                ('license_status', models.CharField()),
                ('license_status_change_date', models.DateTimeField()),
                ('ssa', models.CharField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField()),
            ],
            options={
                'db_table': 'business_licenses_full',
            },
        ),
    ]
