# Generated by Django 4.2.9 on 2024-09-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslicenses',
            name='application_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='application_requirements_complete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_approved_for_issuance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_status_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_term_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_term_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
