# Generated by Django 4.2.9 on 2024-05-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslicenses',
            name='police_district',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='precinct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='ward',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
