# Generated by Django 4.2.9 on 2024-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_businesslicenses_police_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslicenses',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='application_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='application_requirements_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='application_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='business_activity',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='business_activity_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='business_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='conditional_approval',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='date_issued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='doing_business_as_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='legal_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_approved_for_issuance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_status',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_status_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_term_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='license_term_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='site_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='ssa',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='state',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='ward_precinct',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesslicenses',
            name='zip_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
